import '../imports/api/accounts/devLogin.tests'
import '../imports/api/gifts/gifts.methods.tests'
import '../imports/api/gifts/gifts.publications.tests'
import '../imports/api/images/images.tests'
import './helpers.tests'
