#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────


# Push and mail setup for #89 (docs/spec.md §2.5, §3.7). Run from anywhere in
# the repo. Non-secret answers are kept in .push-setup.state (gitignored) so a
# re-run offers them again; secrets go to workspaces/backend/.env.

ROOT=$(git rev-parse --show-toplevel)
cd "$ROOT"
ENV_FILE=.push-setup.state
BACKEND_ENV=workspaces/backend/.env
SECRETS_DIR="$HOME/.secrets/prezentowo"
BUNDLE_ID=com.prezentowo
EXPO_PROJECT_URL=https://expo.dev/accounts/ziarno/projects/prezentowo

# default VAR VALUE — fill VAR with VALUE when the human just pressed Enter.
default() { [[ -n "${!1}" ]] || printf -v "$1" '%s' "$2"; }

# keep_file VAR "what" DEFAULT_PATH — ask where a downloaded secret file is and
# move it into SECRETS_DIR (0600). Sets VAR to its new path, or "" if missing.
# On a re-run, a file kept earlier is reused.
keep_file() {
  local var="$1" what="$2" fallback="$3" src_var="${1}_SRC" src dest kept
  kept=$(_existing "$var" || true)
  if [[ -n "$kept" && -f "$kept" ]]; then
    printf -v "$var" '%s' "$kept"
    printf '  %s✓ kept%s %s at %s\n' "$GREEN" "$RESET" "$what" "$kept"
    return
  fi
  ask "$src_var" "Path to the downloaded $what [$fallback]:"
  default "$src_var" "$fallback"
  # Drag-and-drop pastes a quoted or backslash-escaped path.
  src="${!src_var}"; src="${src//\\/}"; src="${src#[\'\"]}"; src="${src%[\'\"]}"
  src="${src/#\~/$HOME}"
  if [[ ! -f "$src" ]]; then
    warn "no file at $src — download it again and re-run"
    SKIPPED+=("$what")
    printf -v "$var" '%s' ""
    return
  fi
  mkdir -p "$SECRETS_DIR" && chmod 700 "$SECRETS_DIR"
  dest="$SECRETS_DIR/$(basename "$src")"
  [[ "$src" == "$dest" ]] || mv "$src" "$dest"
  chmod 600 "$dest"
  printf -v "$var" '%s' "$dest"
  write_env "$var" "$dest"
}

TOTAL_STAGES=14

banner "Prezentowo — push and mail setup (#89)"

# ── Apple ─────────────────────────────────────────────────────────────────
stage "Apple — APNs key (.p8)"
say "One APNs key serves Expo (inbox pushes) and both Stream providers (chat)."
open_url "https://developer.apple.com/account/resources/authkeys/add"
step "Key name: 'Prezentowo push'. Tick 'Apple Push Notifications service (APNs)'."
step "Configure → if asked: Environment 'Sandbox & Production', restriction 'Team Scoped (All Topics)'."
step "Continue → Register → Download. Apple lets you download it only once."
step "Copy the Key ID shown on that page (10 characters)."
ask APNS_KEY_ID "Key ID:"
write_env APNS_KEY_ID "$APNS_KEY_ID"
ask APPLE_TEAM_ID "Team ID (Membership details) [W6YK2T46G3]:"
default APPLE_TEAM_ID W6YK2T46G3
write_env APPLE_TEAM_ID "$APPLE_TEAM_ID"
keep_file APNS_KEY_PATH "APNs key" "$HOME/Downloads/AuthKey_${APNS_KEY_ID}.p8"
pause

stage "Apple — Push Notifications on the App ID"
open_url "https://developer.apple.com/account/resources/identifiers/list"
step "Open the App ID $BUNDLE_ID."
note "Not listed? '+' → App IDs → App → Explicit bundle ID $BUNDLE_ID."
step "Tick 'Push Notifications' (no certificate needed, the key covers it) → Save."
pause "Done? Press Enter"

# ── Firebase ──────────────────────────────────────────────────────────────
stage "Firebase — project and Android app"
open_url "https://console.firebase.google.com/"
step "Create a project, e.g. 'prezentowo'. Turn Google Analytics OFF (the policy says no analytics)."
step "Project overview → Add app → Android. Package name: $BUNDLE_ID. Register app."
step "Download google-services.json. Skip the SDK steps (native setup is the push slice's job)."
step "Project settings → General: copy the Project ID."
ask FIREBASE_PROJECT_ID "Firebase project ID:"
write_env FIREBASE_PROJECT_ID "$FIREBASE_PROJECT_ID"
ask GOOGLE_SERVICES_SRC "Path to google-services.json [$HOME/Downloads/google-services.json]:"
default GOOGLE_SERVICES_SRC "$HOME/Downloads/google-services.json"
GOOGLE_SERVICES_SRC="${GOOGLE_SERVICES_SRC/#\~/$HOME}"
if [[ -f "$GOOGLE_SERVICES_SRC" ]]; then
  cp "$GOOGLE_SERVICES_SRC" workspaces/mobile/google-services.json
  printf '  %s✓ copied%s → workspaces/mobile/google-services.json (commit it)\n' "$GREEN" "$RESET"
  note "It's client config, not a secret; Android builds read it from the repo."
else
  warn "no file at $GOOGLE_SERVICES_SRC"
  SKIPPED+=("copy google-services.json to workspaces/mobile/")
fi
pause

stage "Firebase — FCM service account key"
open_url "https://console.firebase.google.com/project/${FIREBASE_PROJECT_ID}/settings/serviceaccounts/adminsdk"
step "Generate new private key → Generate key. A JSON file downloads."
step "Then check Project settings → Cloud Messaging: 'Firebase Cloud Messaging API (V1)' is Enabled."
pause "Downloaded? Press Enter"
keep_file FCM_SERVICE_ACCOUNT_PATH "FCM service account JSON" \
  "$(ls -t "$HOME"/Downloads/*firebase-adminsdk*.json 2>/dev/null | head -1 || true)"
pause

# ── Expo ──────────────────────────────────────────────────────────────────
stage "Expo — upload the APNs key"
say "EAS project @ziarno/prezentowo is already linked (extra.eas.projectId in app.json)."
open_url "$EXPO_PROJECT_URL/credentials"
step "iOS → $BUNDLE_ID (add the bundle identifier if it isn't listed)."
step "Push key → add / upload: $APNS_KEY_PATH"
step "Key ID $APNS_KEY_ID, Team ID $APPLE_TEAM_ID."
note "If the web page doesn't offer it: cd workspaces/mobile && npx eas credentials -p ios"
pause "Uploaded? Press Enter"

stage "Expo — upload the FCM service account"
open_url "$EXPO_PROJECT_URL/credentials"
step "Android → $BUNDLE_ID → FCM V1 service account key → upload:"
note "  $FCM_SERVICE_ACCOUNT_PATH"
note "If the web page doesn't offer it: cd workspaces/mobile && npx eas credentials -p android"
note "  → Google Service Account → Manage your FCM V1 service account key → Upload."
pause "Uploaded? Press Enter"

stage "Expo — enhanced push security"
say "With it on, Expo only accepts pushes sent with our access token. Without it,"
say "anyone holding a device's Expo push token can push to that device."
say "Recommended: on. The token lives with the server only."
if confirm "Turn on enhanced push security?"; then
  EXPO_ENHANCED_SECURITY=yes; write_env EXPO_ENHANCED_SECURITY yes
  open_url "https://expo.dev/accounts/ziarno/settings/access-tokens"
  step "Turn on 'Enhanced Security for Push Notifications'."
  step "Create a token (e.g. 'prezentowo-backend') and copy it."
  ENV_FILE="$BACKEND_ENV" ask_secret EXPO_ACCESS_TOKEN "Paste the access token:"
  ENV_FILE="$BACKEND_ENV" write_env EXPO_ACCESS_TOKEN "$EXPO_ACCESS_TOKEN"
  note "Backend .env, next to the Stream keys: settings.json is committed, so no secrets there."
  note "The production server needs EXPO_ACCESS_TOKEN in its environment too."
else
  EXPO_ENHANCED_SECURITY=no; write_env EXPO_ENHANCED_SECURITY no
fi
pause

# ── Stream ────────────────────────────────────────────────────────────────
stage "Stream — push providers and message.new templates"
say "workspaces/backend/scripts/stream-push.mjs creates apn-dev (sandbox),"
say "apn-prod and firebase, and enables message.new on each with our template"
say "(localized title, no badge, Android notification block, eventId passed through)."
note "It uses STREAM_API_KEY / STREAM_API_SECRET from $BACKEND_ENV."
note "A separate production Stream app? Re-run the script there with that app's keys."
if [[ -z "$APNS_KEY_PATH" || -z "$FCM_SERVICE_ACCOUNT_PATH" ]]; then
  warn "the APNs key or the FCM JSON is missing — fix those stages and re-run"
  SKIPPED+=("Stream providers (scripts/stream-push.mjs)")
elif confirm "Create the providers and templates in the Stream app now?"; then
  if ! (cd workspaces/backend && node scripts/stream-push.mjs \
        --apn-key "$APNS_KEY_PATH" --apn-key-id "$APNS_KEY_ID" \
        --apn-team-id "$APPLE_TEAM_ID" \
        --firebase-credentials "$FCM_SERVICE_ACCOUNT_PATH"); then
    warn "stream-push.mjs failed — read the error above, fix it, re-run"
    note "Push v1/v2? Dashboard → the app → Push Notifications → upgrade to v3."
    SKIPPED+=("Stream providers (scripts/stream-push.mjs)")
  fi
else
  SKIPPED+=("Stream providers (scripts/stream-push.mjs)")
fi
pause

stage "Stream — app region"
say "Privacy policy §6 lists Stream as a transfer outside the EEA unless the app is in the EU."
open_url "https://dashboard.getstream.io/"
step "Open the Prezentowo app; its overview shows the region (e.g. 'EU West (Dublin)', 'US East (Ohio)')."
ask STREAM_REGION "Stream region:"
write_env STREAM_REGION "$STREAM_REGION"
pause

# ── Mail ──────────────────────────────────────────────────────────────────
stage "Mail — pick the provider"
say "Transactional mail for magic links and the deletion email. EU-hosted preferred."
note "EU-hosted options include Brevo (FR), Mailjet (FR), Scaleway TEM (FR), Lettermint (NL)."
step "Pick one and create the account."
ask MAIL_PROVIDER "Provider:"
write_env MAIL_PROVIDER "$MAIL_PROVIDER"
ask MAIL_PROVIDER_LOCATION "Where it's hosted (country, EU or US):"
write_env MAIL_PROVIDER_LOCATION "$MAIL_PROVIDER_LOCATION"
pause

stage "Mail — sender on mail.jarno.pl (SPF/DKIM)"
say "Send from a subdomain: jarno.pl is the family's Gmail domain, so its SPF"
say "record stays untouched and Prezentowo's reputation stays apart from it."
step "In $MAIL_PROVIDER, add the sending domain mail.jarno.pl and copy the DNS records it lists."
step "Cloudflare → jarno.pl → DNS: add each record. Names are relative to jarno.pl,"
step "e.g. 'mail' for SPF and '<selector>._domainkey.mail' for DKIM."
step "Wait until $MAIL_PROVIDER shows the domain as verified."
ask MAIL_FROM "Sender [Prezentowo <no-reply@mail.jarno.pl>]:"
default MAIL_FROM "Prezentowo <no-reply@mail.jarno.pl>"
write_env MAIL_FROM "$MAIL_FROM"
node -e '
  const fs = require("fs"), [file, from] = process.argv.slice(1)
  const s = JSON.parse(fs.readFileSync(file, "utf8"))
  s.accounts.passwordless.from = from
  fs.writeFileSync(file, JSON.stringify(s, null, 2) + "\n")
' workspaces/backend/settings.json "$MAIL_FROM"
(cd workspaces/backend && npx --no-install prettier --write settings.json >/dev/null)
printf '  %s✓ set%s accounts.passwordless.from in workspaces/backend/settings.json (commit it)\n' "$GREEN" "$RESET"
pause

stage "Mail — SMTP credentials (MAIL_URL)"
step "In $MAIL_PROVIDER open its SMTP settings and create an SMTP key / password."
ask SMTP_HOST "SMTP host:"
write_env SMTP_HOST "$SMTP_HOST"
ask SMTP_PORT "SMTP port [465]:"
default SMTP_PORT 465
write_env SMTP_PORT "$SMTP_PORT"
ask SMTP_USER "SMTP login:"
ask_secret SMTP_PASSWORD "SMTP password / key:"
scheme=smtp; [[ "$SMTP_PORT" == 465 ]] && scheme=smtps
MAIL_URL=$(node -e '
  const [s, u, p, h, port] = process.argv.slice(1)
  console.log(`${s}://${encodeURIComponent(u)}:${encodeURIComponent(p)}@${h}:${port}`)
' "$scheme" "$SMTP_USER" "$SMTP_PASSWORD" "$SMTP_HOST" "$SMTP_PORT")
ENV_FILE="$BACKEND_ENV" write_env MAIL_URL "$MAIL_URL"
note "Meteor's email package reads MAIL_URL. Production needs it in the server's environment."
pause

# ── Hosting ───────────────────────────────────────────────────────────────
stage "Cloudflare tunnel"
say "Decides whether Cloudflare is listed as a processor in the privacy policy."
if confirm "Does production traffic go through the Cloudflare tunnel?"; then
  CLOUDFLARE_TUNNEL=yes; write_env CLOUDFLARE_TUNNEL yes
else
  CLOUDFLARE_TUNNEL=no; write_env CLOUDFLARE_TUNNEL no
fi
pause

# ── Close the issue ───────────────────────────────────────────────────────
stage "Record it on #89"
PROJECT_ID=$(node -p 'require("./workspaces/mobile/app.json").expo.extra.eas.projectId')
EXPO_TOKEN_NOTE=""; EXPO_TOKEN_VAR=""
if [[ "$EXPO_ENHANCED_SECURITY" == yes ]]; then
  EXPO_TOKEN_NOTE=" (\`EXPO_ACCESS_TOKEN\`)"; EXPO_TOKEN_VAR=", \`EXPO_ACCESS_TOKEN\`"
fi
COMMENT=$(mktemp)
cat > "$COMMENT" <<EOF
Setup done. No secrets in here, only where they live.

- **EAS:** project \`@ziarno/prezentowo\`, \`projectId\` \`$PROJECT_ID\` (committed in \`workspaces/mobile/app.json\`)
- **APNs key:** Key ID \`$APNS_KEY_ID\`, Team ID \`$APPLE_TEAM_ID\`, bundle \`$BUNDLE_ID\`; Push Notifications on the App ID
- **Firebase:** project \`$FIREBASE_PROJECT_ID\`; \`google-services.json\` is committed at \`workspaces/mobile/google-services.json\`
- **Expo credentials:** APNs key and FCM V1 service account uploaded to the EAS project
- **Expo enhanced push security:** $EXPO_ENHANCED_SECURITY$EXPO_TOKEN_NOTE
- **Stream providers:** \`apn-dev\` (\`apn_development: true\`, dev builds), \`apn-prod\`, \`firebase\`; \`message.new\` enabled on each with the templates in \`workspaces/backend/scripts/stream-push.mjs\` (re-run it after editing them)
- **Stream region:** $STREAM_REGION
- **Mail:** $MAIL_PROVIDER ($MAIL_PROVIDER_LOCATION), sender \`$MAIL_FROM\` (\`accounts.passwordless.from\` in \`settings.json\`), SPF/DKIM on \`mail.jarno.pl\`
- **Cloudflare tunnel in production:** $CLOUDFLARE_TUNNEL

**Where the secrets live**
- APNs \`.p8\`, the FCM service-account JSON and the Android upload keystore: the owner's machine (\`~/.secrets/prezentowo/\`); the first two are also uploaded to EAS and Stream, the keystore to EAS
- \`STREAM_API_KEY\`/\`STREAM_API_SECRET\`, \`MAIL_URL\`$EXPO_TOKEN_VAR: \`workspaces/backend/.env\` (gitignored) in development, the server's environment in production
EOF
say "The closing comment:"
printf '\n'; sed 's/^/    /' "$COMMENT"; printf '\n'
if (( ${#SKIPPED[@]} )); then
  warn "Some stages were skipped this run — finish them before closing."
  SKIPPED+=("close #89 with the comment saved at $COMMENT")
elif confirm "Post it and close #89?"; then
  gh issue close 89 --comment "$(cat "$COMMENT")"
  printf '  %s✓ closed%s #89\n' "$GREEN" "$RESET"
else
  SKIPPED+=("close #89 with the comment saved at $COMMENT")
fi
note "Commit workspaces/mobile/google-services.json and workspaces/backend/settings.json."
pause

finish
